name: "Cache and install"

branding:
  icon: package
  color: orange

inputs:
  build:
    description: "Generate production build"
    default: false

runs:
  using: "composite"
  steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.13

    - name: Install Ruby for Shopify CLI
      if: ${{ inputs.build == 'true' }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: "latest"

    - name: Install dependencies
      run: |
        bun install
        bun add --global @shopify/cli @shopify/theme
      shell: bash

    - name: Tools cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/node_modules/.cache/
        key: tools-cache-${{ github.base_ref }}
        restore-keys: |
          tools-cache-

    - name: Generate production build
      if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
