on:
  workflow_call:
    inputs:
      IGNORED_FILES_PUSH:
        type: string
      IGNORED_FILES_PULL:
        type: string
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true

env:
  SHOPIFY_CLI_NO_ANALYTICS: true
  SHOPIFY_CLI_TTY: 0
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: ${{ github.workspace }}/dist

jobs:
  create_or_update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOP }}
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.PASSWORD }}
    steps:
      - name: Prepare
        uses: alruban/shopify-actions/.github/actions/cache-and-install@main
        with:
          build: true

      - name: Update (+ create) preview theme
        uses: alruban/shopify-actions/.github/actions/theme-preview-create@main
        with:
          IGNORED_FILES_PUSH: ${{ inputs.IGNORED_FILES_PUSH }}
          IGNORED_FILES_PULL: ${{ inputs.IGNORED_FILES_PULL }}
