on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true
      THEME_ID:
        required: true

env:
  SHOPIFY_CLI_NO_ANALYTICS: true
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: ${{ github.workspace }}/dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub deployment
        id: deployment
        uses: altinukshini/deployment-action@releases/v1
        with:
          token: ${{ github.token }}
          environment: production

      - name: Prepare
        uses: alruban/shopify-actions/.github/actions/cache-and-install@main
        with:
          build: true

      - name: Update deployment status (Inprogress)
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "in_progress"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          description: "Deploying code for branch: "

      - name: Deploy theme
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOP }}
          SHOPIFY_FLAG_THEME_ID: ${{ secrets.THEME_ID }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.PASSWORD }}
        uses: alruban/shopify-actions/.github/actions/theme-deploy@main

      - name: Update deployment status (success)
        if: ${{ success() }}
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: ${{ failure() }}
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
