on:
  workflow_call:
    inputs:
      disableThemeCheck:
        type: boolean

env:
  SHOPIFY_CLI_NO_ANALYTICS: true
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: ${{ github.workspace }}/dist

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: alruban/shopify-actions/.github/actions/cache-and-install@main

      - name: Lint CSS
        run: pnpm run lint:css

      - name: Lint JS
        run: pnpm run lint:js

  theme-check:
    runs-on: ubuntu-latest
    if: inputs.disableThemeCheck != true
    steps:
      - name: Prepare
        uses: alruban/shopify-actions/.github/actions/cache-and-install@main
        with:
          build: true

      - name: Theme check
        run: pnpm run lint:theme
